// Generated by Selenium IDE
package com.fluffy.universe.models.ui;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\hedg3\\Downloads\\universe\\universe-master\\src\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registration() {
    driver.get("http://127.0.0.1:7000/");
    driver.manage().window().setSize(new Dimension(1038, 1026));
    driver.findElement(By.linkText("Sign up")).click();
    driver.findElement(By.id("sign-up__first-name")).click();
    driver.findElement(By.id("sign-up__first-name")).sendKeys("alina");
    driver.findElement(By.id("sign-up__last-name")).sendKeys("shelest");
    driver.findElement(By.id("sign-up__email")).click();
    driver.findElement(By.id("sign-up__email")).sendKeys("alyashelya+ll@gmail.com");
    driver.findElement(By.id("sign-up__password")).click();
    driver.findElement(By.id("sign-up__confirm-password")).sendKeys("5LCthfUeqsnUXLe!");
    driver.findElement(By.id("sign-up__password")).sendKeys("5LCthfUeqsnUXLe!");
    driver.findElement(By.id("sign-up__confirm-password")).click();
    driver.findElement(By.cssSelector(".form__button")).click();
    driver.findElement(By.cssSelector(".alert__button")).isDisplayed();
    driver.findElement(By.cssSelector(".alert__button")).click();
    driver.findElement(By.cssSelector(".dropdown__link:nth-child(2)")).isDisplayed();
    driver.close();
  }
}
